openapi: 3.0.0
info:
  title: Expense Classifier API
  description: API for translating and classifying expenses using Google Generative AI and speech-to-text using ElevenLabs.
  version: 1.0.0

servers:
  - url: http://localhost:5050

paths:
  /:
    get:
      summary: Health check
      description: Returns the running status of the API.
      responses:
        '200':
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: running

  /classify-expense:
    post:
      summary: Translate and classify an expense
      description: >
        Translates the input text between English and Romanian, clarifies the meaning,
        and classifies it into one of the provided categories.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Way brat azi am cheltuit 500 di lei pi ciupaciupsuri"
                categories:
                  type: array
                  items:
                    type: string
                  example: ["going out", "house expense", "groceries"]
      responses:
        '200':
          description: Successful classification
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_text:
                    type: string
                    example: "Way brat azi am cheltuit 500 di lei pi ciupaciupsuri"
                  translated_text:
                    type: string
                    example: "Today I spent 500 lei on lollipops"
                  classified_items:
                    type: array
                    items:
                      type: string
                    example: ["groceries"]
                  status:
                    type: string
                    example: success
        '400':
          description: Bad request (missing text or categories)
        '500':
          description: Internal server error (translation or classification failed)

  /speech-to-text:
    post:
      summary: Convert speech to text and classify expense
      description: >
        Converts audio file to text using ElevenLabs Scribe, translates if needed,
        and classifies the expense into provided categories.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: Audio file (MP3, WAV, etc.)
                categories:
                  type: array
                  items:
                    type: string
                  description: Optional expense categories (defaults to ["going out", "house expense", "groceries"])
                  example: ["going out", "house expense", "groceries"]
      responses:
        '200':
          description: Successful speech-to-text and classification
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_text:
                    type: string
                    example: "Today I spent 500 lei on lollipops"
                  translated_text:
                    type: string
                    example: "Today I spent 500 lei on lollipops"
                  classified_items:
                    type: array
                    items:
                      type: string
                    example: ["groceries"]
                  status:
                    type: string
                    example: success
        '400':
          description: Bad request (no audio file provided)
        '500':
          description: Internal server error (speech processing, translation, or classification failed)

  